services:
  webbankingclient:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
      - 9230:9230
    command: npm run dev

    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
