services:
  webbankingserver:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      SECRET_ACCESS_TOKEN: WebBankingAppSecretKey
      SECRET_REFRESH_TOKEN: WebBankingAppSecretKeyRefresh
      PORT: 3000
      EMAIL_PASSWORD: 'uaak cfyn imgo bcxg'
      EMAIL_USERNAME: 'shai.yarden@gmail.com'
      URI: 'mongodb+srv://yarden:123123123123@iotdatabase.yposswl.mongodb.net/WebBankingApp?retryWrites=true&w=majority&appName=IOTDataBase'
    ports:
      - 3000:3000
      - 9229:9229
      - 5173:5173
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/server/node_modules
      - /app/client/node_modules
    depends_on:
      redis:
        condition: service_healthy
    command: sh -c "npm run devstart --prefix server & npm run dev --prefix client" # npm run devstart --prefix server

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
