const dotenv = require('dotenv');
dotenv.config();

const { URI, PORT, SECRET_ACCESS_TOKEN, SECRET_REFRESH_TOKEN, EMAIL_PASSWORD, EMAIL_USERNAME } = process.env;

module.exports = { URI, PORT, SECRET_ACCESS_TOKEN, SECRET_REFRESH_TOKEN, EMAIL_PASSWORD, EMAIL_USERNAME };
